const actionTypes = {
	"NEW_MOVE": "NEW_MOVE",
	"GENERATE_CANDIDATE_MOVES": "GENERATE_CANDIDATE_MOVES",
	"CLEAR_CANDIDATE_MOVES": "CLEAR_CANDIDATE_MOVES",
	"PROMOTION_OPEN": "PROMOTION_OPEN",
	"PROMOTION_CLOSE": "PROMOTION_CLOSE",
	"CAN_CASTLE": "CAN_CASTLE",
	"STALEMATE": "STALEMATE",
	"INSUFFICIENT_MATERIAL": "INSUFFICIENT_MATERIAL",
	"THREEFOLD_REPETITION": "THREEFOLD_REPETITION",
	"WIN": "WIN",
	"NEW_GAME": "NEW_GAME",
	"TAKE_BACK": "TAKE_BACK",
	"UPDATE_LOST_FIGURES": "UPDATE_LOST_FIGURES",
	"REMOVE_LOST_FIGURE": "REMOVE_LOST_FIGURE",
	"UPDATE_LAST_MOVE": "UPDATE_LAST_MOVE",

	"TOOGLE_MENU": "TOOGLE_MENU",
	"SET_HIGHTLIGHTED_MENU_ITEM": "SET_HIGHTLIGHTED_MENU_ITEM",
	"ON_CHANGE_MENU_ITEM": "ON_CHANGE_MENU_ITEM",
	"SET_COORDS": "SET_COORDS",

	"AUTH_SUCCESS": "AUTH_SUCCESS",
	"AUTH_LOGOUT": "AUTH_LOGOUT",
}

export default actionTypes;